"""Regression tests against a real ``dbt parse`` output.

Our hand-written ``tests/fixtures/manifest.json`` is the easy case — we
control its shape and fields. Real dbt manifests carry many more keys
(``compiled_code``, ``raw_code``, ``contract``, ``constraints``,
``primary_key``, ``time_spine``, ``deprecation_date``, ``access``, ...)
and shift between dbt versions.

This fixture was generated by running ``dbt parse`` + ``dbt docs generate``
against the bundled example project on **dbt-core 1.11.8** with
**manifest schema v12**. It's pruned to the keys our parser reads
(``metadata``, ``nodes``, ``sources``) so the file stays small.

To regenerate (e.g., when bumping dbt support floor):

    cd examples/jaffle_shop_features
    DBT_PROFILES_DIR=. dbt seed && dbt run && dbt docs generate
    cp target/manifest.json ../../tests/fixtures/real/
    cp target/catalog.json ../../tests/fixtures/real/
    # Then prune manifest.json — keep only metadata, nodes, sources.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from dbt_features.parser import parse_project
from dbt_features.schema import FeatureType

REAL = Path(__file__).parent / "fixtures" / "real"


@pytest.fixture()
def real_project_dir(tmp_path: Path) -> Path:
    """Lay out a tmp project that mimics dbt's standard layout."""

    target = tmp_path / "target"
    target.mkdir()
    (target / "manifest.json").write_text((REAL / "manifest.json").read_text())
    (target / "catalog.json").write_text((REAL / "catalog.json").read_text())
    return tmp_path


def test_parses_real_manifest_without_error(real_project_dir: Path) -> None:
    """The headline regression — our parser must not choke on a manifest
    we didn't author. Catches assumptions about field presence/shape."""

    cat = parse_project(real_project_dir)
    assert cat.project_name == "jaffle_features"
    assert len(cat.feature_groups) == 2  # daily + lifetime, matches example


def test_real_manifest_extracts_features(real_project_dir: Path) -> None:
    cat = parse_project(real_project_dir)
    daily = next(g for g in cat.feature_groups if g.name == "customer_features_daily")
    feature_names = {f.name for f in daily.features}
    # is_feature: true on three columns in the example
    assert feature_names == {"customer_id", "orders_count_7d", "is_repeat_customer"}


def test_real_catalog_json_warehouse_types_picked_up(real_project_dir: Path) -> None:
    """In the real run, DuckDB normalizes integers to BIGINT. Our parser
    should pick this up from catalog.json and not fall back to whatever
    the manifest declared."""

    cat = parse_project(real_project_dir)
    daily = next(g for g in cat.feature_groups if g.name == "customer_features_daily")
    orders = next(f for f in daily.features if f.name == "orders_count_7d")
    # Real warehouse type from catalog.json — DuckDB widens INT -> BIGINT
    assert orders.column_type == "BIGINT"


def test_real_manifest_metadata_carried_through(real_project_dir: Path) -> None:
    """Owner, freshness, tags from the example's _features.yml should
    survive the round trip through dbt parse -> our parser."""

    cat = parse_project(real_project_dir)
    daily = next(g for g in cat.feature_groups if g.name == "customer_features_daily")
    assert daily.owner == "growth-team@jaffle.com"
    assert "customer" in daily.tags
    assert daily.freshness is not None
    assert daily.freshness.warn_after.count == 36
    assert daily.timestamp_column == "feature_date"


def test_real_manifest_lineage_resolved(real_project_dir: Path) -> None:
    """The example's lifetime model depends on stg_orders directly (not
    on customer_features_daily as our hand-written fixture has it).
    Lineage must reflect what dbt actually produced."""

    cat = parse_project(real_project_dir)
    daily = next(g for g in cat.feature_groups if g.name == "customer_features_daily")
    upstream_names = {r.name for r in daily.upstream}
    assert "stg_orders" in upstream_names
    # Downstream — consumer_dashboard_metrics consumes it (non-feature)
    assert any(r.name == "consumer_dashboard_metrics" for r in daily.downstream)


def test_real_manifest_picks_correct_resource_types(real_project_dir: Path) -> None:
    """Real manifests contain non-model nodes (tests, snapshots, seeds,
    sources). Our parser must scan only models for feature tables.

    The example has at least one ``seed`` (raw_orders) — that must NOT
    appear as a feature table, no matter what its meta block says."""

    raw = json.loads((REAL / "manifest.json").read_text())
    resource_types = {n["resource_type"] for n in raw["nodes"].values()}
    # Confirm there's a non-model in the manifest so the test is meaningful
    assert resource_types - {"model"}, (
        "fixture has only models — regression test is no-op. "
        "Regenerate with seeds/tests/snapshots present."
    )

    cat = parse_project(real_project_dir)
    seed_names = [
        n["name"] for n in raw["nodes"].values() if n["resource_type"] == "seed"
    ]
    for seed_name in seed_names:
        assert all(g.name != seed_name for g in cat.feature_groups), (
            f"Seed {seed_name} mistakenly classified as a feature table"
        )


def test_real_features_have_warehouse_types(real_project_dir: Path) -> None:
    """Every feature that maps to a real column should have a column_type
    pulled from catalog.json — that's what makes the rendered table
    informative on the feature page."""

    cat = parse_project(real_project_dir)
    for group in cat.feature_groups:
        for feature in group.features:
            # customer_id is varchar, the rest are numeric/boolean
            assert feature.column_type is not None, (
                f"{group.name}.{feature.name} has no warehouse type"
            )


def test_real_feature_types_parsed_correctly(real_project_dir: Path) -> None:
    """The example declares feature_type for every column. Verify the
    enum round-trips."""

    cat = parse_project(real_project_dir)
    daily = next(g for g in cat.feature_groups if g.name == "customer_features_daily")
    types = {f.name: f.feature_type for f in daily.features}
    assert types["customer_id"] == FeatureType.IDENTIFIER
    assert types["orders_count_7d"] == FeatureType.NUMERIC
    assert types["is_repeat_customer"] == FeatureType.BOOLEAN
