name: jaffle_features
version: '0.1.0'
profile: jaffle_features
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_features:
    +materialized: table
